### PR TITLE
688 ObjectNullReferenceException from resource manager

### LINKED ISSUE #688: Object reference not set to an instance of an object - better error message handling
**Environment:**

Windows 10, 64-bit

Test Automation 9.18.0-rc.1

**Steps to reproduce:**

* Drop [ExampleRealm.dll](/uploads/2ef1013af72dedcc55ff3d7c988dee46/ExampleRealm.dll) in clean TAP v9.16.4 installation.
* Start Editor
* Add MyStep
* Add MyInstrument1 and MyInstrument2
* Give MyInstrument2 as a resource into MyInstrument1
* Give MyInstrument1 as a resource into MyStep
* Remove MyInstrument2
* Run a plan

**Actual result:**

image

(Please also attach a log file from %TAP_PATH%\SessionLogs\ that shows the issue when possible/relevant)

**Expected result:**

Better error handling message.

**Other remarks:**

### PR DESCRIPTION
**Pull request by rmadsen-ks**
- added possibility of figuring out which exception caused the test plan to stop.
- added unit test that shows the error.

Close #688

### CODE REVIEW

File: Engine/ResourceTaskManager.cs [hunk 1]
```diff
@@ -398,7 +398,11 @@ void beginOpenResoureces(List<ResourceNode> resources, CancellationToken cancell
                 foreach (var res in resources)
                 {
                     if (untouched.Contains(res.Resource))
-                        throw new Exception($"Deleted resource being used by {res.Depender.DeclaringType}.");
+                    {
+                        if(res.Depender != null)
+                            throw new Exception($"Deleted resource '{res.Resource}' being used by {res.Depender.DeclaringType}.");
+                        throw new Exception($"Deleted resource '{res.Resource}' is in used.");
```
Comment (alnlarsen) [inline Engine/ResourceTaskManager.cs:404]:
```suggestion
                            throw new Exception($"Deleted resource '{res.Resource}' is in use by {res.Depender.DeclaringType}.");
                        throw new Exception($"Deleted resource '{res.Resource}' is in use.");
```

**Review by alnlarsen — CHANGES_REQUESTED** [review]
This looks like a great fix. Just one minor suggestion.

**Review by alnlarsen — APPROVED** [review]
Awesome!
