### PR TITLE
1166 PackageReference to drive bug: Fix issue with paths being trimmed

### LINKED ISSUE #1166: Package references not on C:\ fail to install
**Describe the bug**

When adding a package reference from a repository that is not rooted on the C:\\, that package does not install and the build fails.

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.21.0

**To Reproduce**

1.  Place the same TapPackage file in several directories on different drives. (OS drive, USB and mapped network drive)

2. Create a new package which references the first.

3. Repeatedly build the new package, each time changing the repository location, clearing the package from the PackageCache and uninstalling the package from the OpenTAP installation in the build directory.

**Actual behavior**

Build fails when using both the USB drive and the mapped network drive, though build output differs.

USB:
image
image

Mapped Network Drive:
image
image

**Expected behavior**

The package should build successfully in all scenarios.

**Additional context**

Contents of the project file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTAP" Version="9.21.0" />
  </ItemGroup>

  <ItemGroup>
    <!--<OpenTapPackageReference Include="Package1" Version="any" Repository="C:\temp" />-->
    <OpenTapPackageReference Include="Package1" Version="any" Repository="E:\opentap" />
    <!--<OpenTapPackageReference Include="Package1" Version="any" Repository="Z:\test\Temp" />-->
  </ItemGroup>

  <Target Name="CleanReferencePackage"  BeforeTargets="BeforeBuild">
    <Exec Command=".\tap package uninstall Package1 --ignore-missing" WorkingDirectory="$(TargetDir)" />
    <ItemGroup>
      <PackageInCache Include="$(LOCALAPPDATA)\OpenTAP\PackageCache\Package1*" />
    </ItemGroup>
    <Delete Files="@(PackageInCache)" />
  </Target>
</Project>
```

### PR DESCRIPTION
**Pull request by rmadsen-ks**
- Also added that drive-letter + '':' (D:) is a valid identifier on Windows. This could be useful for people storing packages on e.g USB or network drives.

Close #1166

### CODE REVIEW

File: Package/Repositories/FilePackageRepository.cs [hunk 1]
```diff
@@ -39,6 +39,14 @@ public class FilePackageRepository : IPackageRepository, IPackageDownloadProgres
         /// <exception cref="NotSupportedException">Path is not a valid file package repository</exception>
         public FilePackageRepository(string path)
         {
+            // if path is the path root, for example C: and the path is not "/".
+            // then we need to add a '\' so "C:" becomes "C:\".
+            // On other systems (Linux, mac, .. where path == "/") we do nothing.
+            if (Path.IsPathRooted(path) && path !="/" && Path.GetPathRoot(path) == path)
+            {
+                path = Path.GetPathRoot(path) + Path.DirectorySeparatorChar;
+            }
```
Comment (alnlarsen) [inline Package/Repositories/FilePackageRepository.cs:48]: This turns `C:\` into `C:\\`

**Review by alnlarsen — CHANGES_REQUESTED** [review]
There appears to be one minor issue

File: Package/Repositories/FilePackageRepository.cs (hunk 1 above)
Comment (rmadsen-ks) [reply Package/Repositories/FilePackageRepository.cs]: This was fixed.

File: Package.UnitTests/FilePackageRepoTest.cs [hunk 2]
```diff
@@ -0,0 +1,19 @@
+using NUnit.Framework;
+namespace OpenTap.Package.UnitTests
+{
+    [TestFixture]
+    public class FilePackageRepoTest
+    {
+        [TestCase("C:\\")]
```
[the remark this answers is not in the document]
Comment (rmadsen-ks) [reply Package.UnitTests/FilePackageRepoTest.cs]: Yes, but it is a bit har to make a general test for it since \ (like /) can mean many things.

File: Package.UnitTests/FilePackageRepoTest.cs [hunk 3]
```diff
@@ -1,18 +1,24 @@
...
-        [TestCase("D:")]
-        [TestCase("D:/")]
-        [TestCase("/")]
-        public void TestRootFileSystemPath(string okPath)
+        [TestCase("C:\\", "C:\\")]
+        [TestCase("/", null)] // this might be C or D or ... depending on the current drive.
+        [TestCase("C:", "C:\\")]
+        [TestCase("D:", "D:\\")]
+        [TestCase("D:\\", "D:\\")]
+        [TestCase("/", null)]
```
Comment (alnlarsen) [inline Package.UnitTests/FilePackageRepoTest.cs:13]: The "/" case is here twice. Did you mean to put "\\\\" or remove it?

**Review by alnlarsen — CHANGES_REQUESTED** [review]
It looks like you added the same test twice

**Review by alnlarsen — APPROVED** [review]
Looks good!
