### PR TITLE
1411 Parameterization Breaks After PluginManager search: Fix

### LINKED ISSUE #1411: Parameterizations breaks after PluginManager.Search
After plugin search external parameters breaks. 

This is probably due to cache invalidation and that every type gets new objects.

Reproduced by:

```cs
            var plan = new TestPlan();
            var delay = new DelayStep();
            plan.ChildTestSteps.Add(delay);
            
            TypeData.GetTypeData(delay).GetMember(nameof(DelayStep.DelaySecs))
                .Parameterize(plan, delay, nameof(DelayStep.DelaySecs));
            
            var xmlPreSearch = plan.SerializeToString();
            
            // searching for plugins should not affect serialization.
            PluginManager.Search();
            var xmlPostSearch = plan.SerializeToString();
            
            Assert.AreEqual(xmlPreSearch, xmlPostSearch);

```

### PR DESCRIPTION
**Pull request by rmadsen-ks**
Fixed the issue by implementing Equality for MemberData. This is required for a lookup table inside the ExternalParameterSerializer. Otherwise when serialization is done it will not recognize the new MemberData instance as the same one as in the parameter.

Added a unit test to verify the fix.

Close #1411

### CODE REVIEW

File: Engine.UnitTests/ExternalTestPlanParameterTest.cs [hunk 1]
```diff
@@ -494,5 +494,26 @@ public void MultiSelectEditParametersDisabled()
...
+            
+            var preMember = TypeData.GetTypeData(delay).GetMember(nameof(DelayStep.DelaySecs))
+                .Parameterize(plan, delay, nameof(DelayStep.DelaySecs));
+            
+            var xmlPreSearch = plan.SerializeToString();
+            
+            // searching for plugins should not affect serialization.
+            PluginManager.Search();
+            var xmlPostSearch = plan.SerializeToString();
+            TypeData.GetTypeData(plan).GetMember(preMember.Name);
```
Comment (alnlarsen) [inline Engine.UnitTests/ExternalTestPlanParameterTest.cs:513]: Does this lookup serve a purpose?

File: Engine/Reflection/DotNetTypeData.cs [hunk 2]
```diff
@@ -184,5 +184,18 @@ ITypeData getTypeDescriptor()
...
+        public override bool Equals(object obj)
+        {
+            if (obj is MemberData m && m.Member == Member)
+                return true;
+            return false;
+        }
+        /// <summary> GetHash for MemberData. </summary>
+        public override int GetHashCode()
+        {
+            return Member.GetHashCode() * 32143211;
```
Comment (alnlarsen) [inline Engine/Reflection/DotNetTypeData.cs:198]: What is the point of this multiplication?

File: Engine/DynamicMemberTypeDataProvider.cs [hunk 3]
```diff
@@ -467,6 +467,7 @@ internal static ParameterMemberData ParameterizeMember(object target, IMemberDat
             if (member == null) throw new ArgumentNullException(nameof(member));
             if (source == null) throw new ArgumentNullException(nameof(source));
             if (name == null) throw new ArgumentNullException(nameof(name));
+            if (source == target) throw new InvalidOperationException("Source and target cannot be the same object.");
```
Comment (alnlarsen) [inline Engine/DynamicMemberTypeDataProvider.cs:470]: This fix looks unrelated to this issue. Did you encounter this scenario while working on this?

**Review by alnlarsen — CHANGES_REQUESTED** [review]
I think this looks like a good solution, but I have a few questions

File: Engine/DynamicMemberTypeDataProvider.cs (hunk 3 above)
Comment (rmadsen-ks) [reply Engine/DynamicMemberTypeDataProvider.cs:470]: This happened when I tried to implement the test. If the check is not done a stack overflow exception will occur.

File: Engine/Reflection/DotNetTypeData.cs (hunk 2 above)
Comment (rmadsen-ks) [reply Engine/Reflection/DotNetTypeData.cs:198]: I scramble the hash to reduce the risk of collisions. Otherwise they'd have the same hash value as the Member and this would not be every "random".

Comment (rmadsen-ks) [reply Engine/Reflection/DotNetTypeData.cs:198]: It's not super important. If there were more things being hashed together it would be.

**Review by alnlarsen — APPROVED** [review]
Looks great!
