### PR TITLE
481 Re-add the childStepsChanged event when ChildTestSteps instance is changed

### LINKED ISSUE #481: Legacy Sweep Loop Range Can Iterate paramters of deleted steps
**Environment:**

Windows 10, 64-bit

OpenTAP 9.17.3
OpenTAP 9.16.4

**Steps to reproduce:**

1. Import/Open SweepLoopRange.TapPlan and delete Dialog step then run test plan  [SweepLoopRange.zip](https://github.com/opentap/opentap/files/8322462/SweepLoopRange.zip)
2. Create a new test plan with a sweep loop(range) and a Dialog step, add Timeout sweep parameter, then delete Dialog step and run the test plan

**Actual result:**

1. Animation

2. Animation

(Please also attach a log file from %TAP_PATH%\SessionLogs\ that shows the issue when possible/relevant)

**Expected result:**

After child step deletion, Sweep parameters should be cleared and error should be shown when test plan run.

**Other remarks:**

### PR DESCRIPTION
**Pull request by alnlarsen**
During serialization we overwrite the value of TestStepList on teststeps
which caused issues for Sweep Loop Range because it sets up the event in its constructor.

It now listens for the PropertyChanged event and sets up the callback in this case.

Closes #481

### CODE REVIEW

File: Engine/SerializerPlugins/ObjectSerializer.cs [hunk 1]
```diff
@@ -238,12 +238,23 @@ public virtual bool TryDeserializeObject(XElement element, ITypeData t, Action<o
...
-                                        if (false == Equals(current, x))
-                                        { // for some value-like type, it may be needed
-                                            // to set the parent object when a property is changed
-                                            // example: complex test plan parameters.
-                                            setter(newobj);
+                                        // Some plugins configure event handlers for ChildTestSteps in their constructor.
+                                        // If the list is already initialized, we should add the content of the newly deserialized list to the current list instead of overwriting it.
+                                        if (x is TestStepList newList && current is TestStepList currentList)
+                                        {
+                                            currentList.AddRange(newList);
```
Comment (rmadsen-ks) [inline Engine/SerializerPlugins/ObjectSerializer.cs:245]: If the test step constructor adds a couple of steps, would this cause some issues?

**Review by rmadsen-ks — CHANGES_REQUESTED** [review]
I am not sure that this is the correct solution. It is just important that test step developers knows that if one listen to child steps changed, it is important to also handle changes in the getter/setter.

**Review by rmadsen-ks — APPROVED** [review]
Looks good!

File: BasicSteps/SweepLoopRange.cs [hunk 2]
```diff
@@ -185,8 +186,15 @@ public SweepLoopRange()
...
 
             ChildTestSteps.ChildStepsChanged += childStepsChanged;
+            PropertyChanged += SweepLoopRange_PropertyChanged;
         }
-        
+
+        void SweepLoopRange_PropertyChanged(object sender, PropertyChangedEventArgs e)
+        {
+            if (e.PropertyName == nameof(ChildTestSteps))
+                ChildTestSteps.ChildStepsChanged += childStepsChanged;
```
Comment (AsgerIversen) [inline BasicSteps/SweepLoopRange.cs:195]: Can we remove the eventhandler from the old childsteps instance here to avoid leaking that?

**Review by AsgerIversen — CHANGES_REQUESTED** [review]

File: BasicSteps/SweepLoopRange.cs (hunk 2 above)
Comment (rmadsen-ks) [reply BasicSteps/SweepLoopRange.cs:195]: This is not possible in a PropertyChanged event handler, but that should not be a problem, since 'this' no longer points to that instance of ChildTestSteps that event handler should be collectable by GC.

Comment (AsgerIversen) [reply BasicSteps/SweepLoopRange.cs:195]: You are right. I just had it turned around in my head.

**Review by AsgerIversen — APPROVED** [review]
