### PR TITLE
808 Force Install Version Behavior: Fix

### LINKED ISSUE #808: Behavior change with old plugins 9.19 vs 9.18
**Describe the bug**

9.18 would install a plugin missing a dependency with `-f` but 9.19 will not

I am reporting this as a behavior change, not sure if this is a bug or a feature

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.19.0-rc1

**To Reproduce**

1. `tap package install RemoteSigntool -r "http://packages.opentap.keysight.com" -f`

**Actual behavior**

on **9.19.0-rc.1**, the plugin is not installed. Log [SessionLog 2022-09-14 00-27-07.txt](https://github.com/opentap/opentap/files/9563842/SessionLog.2022-09-14.00-27-07.txt). Note: It will be installed if `--version any` is specified

image

on **9.18.5**, the plugin is installed. Log [SessionLog 2022-09-14 00-27-22.txt](https://github.com/opentap/opentap/files/9563853/SessionLog.2022-09-14.00-27-22.txt)

image

### PR DESCRIPTION
**Pull request by rmadsen-ks**
- Reverted so that AnyRelease.ToString() => "". Previously an empty version meant AnyRelease and some code might still use this convension.
- Also Made a more explicit check for 'AnyRelease in HttpPackageRepository'

Close #808

### CODE REVIEW

File: Package/PackageSpecifier.cs [hunk 1]
```diff
@@ -194,7 +198,7 @@ public override string ToString()
             if (this == VersionSpecifier.Any)
                 return "Any";
             if (this == VersionSpecifier.AnyRelease)
-                return "Any Release";
+                return "";
```
Comment (alnlarsen) [inline Package/PackageSpecifier.cs:201]: Can we add "AnyRelease" / "AnyRelease" / "" to the VersionSpecifier.Parse method?

**Review by alnlarsen — CHANGES_REQUESTED** [review]

**Comment by alnlarsen** [comment]
This fixes the issue observed with `RemoteSigntool`

File: Package/PackageSpecifier.cs (hunk 1 above)
Comment (rmadsen-ks) [reply Package/PackageSpecifier.cs:201]: Lets do this at a later point

**Comment by alnlarsen** [comment]
Okay, I have opened a separate issue for parsing the `AnyRelease` specifier: https://github.com/opentap/opentap/issues/836
