### PR TITLE
1528 available values multi select bug

### LINKED ISSUE #1528: Available Values Example: SelectedValues cannot be modified in case of multiple steps selected
**Describe the bug**

When more than one `Available Values Example` is selected, `SelectedValues` test step settings cannot be modified
**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.24.0-rc.1

**To Reproduce**
1. Add two `Available Values Example` test steps
2. Select both steps
3. Edit `SelectedValues` test steps settings

**Actual behavior**
multiple selection

### PR DESCRIPTION
**Pull request by rmadsen-ks**
Close #1528

### CODE REVIEW

File: Engine.UnitTests/AnnotationTest.cs [hunk 1]
```diff
@@ -2693,5 +2693,53 @@ public void TestTimeSpanAnnotationError()
...
+            Assert.AreEqual(0, multi.Selected.Cast<object>().Count());
+
+            // Select two values across both steps.
+            multi.Selected = new List<object> { availArray[0], availArray[2] };
+            a.Write();
+            a.Read();
+
+            // The change should be reflected in both underlying steps.
+            CollectionAssert.AreEquivalent(new[] { "One", "Three" }, step1.SelectedValues);
+            CollectionAssert.AreEquivalent(new[] { "One", "Three" }, step2.SelectedValues);
```
Comment (alnlarsen) [inline Engine.UnitTests/AnnotationTest.cs:2737]:
```suggestion
            CollectionAssert.AreEquivalent(new[] { "One", "Three" }, step2.SelectedValues);
            Assert.IsFalse(ReferenceEquals(step1.SelectedValues, step2.SelectedValues));
```

**Review by alnlarsen — CHANGES_REQUESTED** [review]
Looks good but I would like one extra assert

**Review by alnlarsen — APPROVED** [review]
looks good
