### PR TITLE
781 Scpi Instrument Not Supported on ubuntu 2204: Fix

### LINKED ISSUE #781: ScpiInstrument not supproted on Ubuntu 22.04
we are using libdl.so, but it has been renamed in a way that prevents .net from loading it.

the new name is libdl.so.2, we need to add code to check for that one if the first is unable to load.

### PR DESCRIPTION
**Pull request by rmadsen-ks**
- Added support for loading libdl.so.2 when using Visa.

This was manually tested to work on SCPI enabled instruments on Ubuntu 2204.

Close #781

### CODE REVIEW

File: Engine/LibDl.cs [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+        }
+    }
+
+    public static IntPtr Sym(IntPtr lib, string name) => libdl.dlsym(lib, name);
+
+    public static IntPtr Load(string name)
+    {
+        clearError();
+        IntPtr p = load(name);
+        if (p == IntPtr.Zero)
```
Comment (alnlarsen) [inline Engine/LibDl.cs:103]: This check looks pointless. Did you mean to return null?

File: Engine/LibDl.cs [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+
+    public static string GetError()
+    {
+        var error = libdl.dlerror();
+        if (IntPtr.Zero == error) return null;
+        return Marshal.PtrToStringAuto(error);
+
+    }
+    
+    static void checkError()
```
Comment (alnlarsen) [inline Engine/LibDl.cs:18]: It doens't look like this method is used?

File: Engine/LibDl.cs [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+    {
+        var error = libdl.dlerror();
+        if (error != IntPtr.Zero)
+            throw new Exception("Unable to load python: " + error.ToString());
```
Comment (alnlarsen) [inline Engine/LibDl.cs:22]: What is this about python?

**Review by alnlarsen — CHANGES_REQUESTED** [review]
It looks like we prefer libdl2 over libdl1 if they are both available. Can this cause issues?

**Review by alnlarsen — APPROVED** [review]
Looks good now
