### PR TITLE
332 Expand/Collapse TestSteps

### LINKED ISSUE #332: API for expanding/collapsing test steps heirachies
Based on user request. It would be helpful to be able to control the expand/collapse state from an API, and also save the state as a part of the test plan.

### LINKED ISSUE #570: XmlAttributeAttribute does not work for dynamic IMemberData
Dynamically added IMemberData implementations which has the XmlAttributeAttribute are able to serialize, but not deserialize.

Needed for #332

### PR DESCRIPTION
**Pull request by rmadsen-ks**
- Implemented the expanded/collasped state as a dynamic member property.
- Fixed bug in XML deserialization that caused XmlAttributeAttribute not work for dynamically created properties.
- Added a unit test that tests the UI folding state.

Closes #332 
Closes #570

### CODE REVIEW

File: Engine/UiFolding.cs [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+        public static void SetFolding(object obj, bool? expanded)
+        {
+            UiFoldingProperty.SetValue(obj, expanded switch
+            {
+                null => null,
+                true => "expand",
+                false => "collapse"
+            });
+        }
+        /// <summary>  Sets the current collapsed or folding state. If not set it will return null. </summary>
```
Comment (alnlarsen) [inline Engine/UiFolding.cs:39]:
```suggestion
        /// <summary>  Gets the current folding state. If not set it will return null. </summary>
```

**Review by alnlarsen — CHANGES_REQUESTED** [review]
The implementation looks good and seems to work as intended, but it looks like one of the doc comments are incorrect.

**Comment by rmadsen-ks** [comment]
@AsgerIversen, should we create a new namespace for this?

**Comment by AsgerIversen** [comment]
> @AsgerIversen, should we create a new namespace for this?

If we were doing this from scratch, we probably should have a UI namespace. If we create one now, we will not be able to move things like UserInput, IUserInterface, IMenuModel, IconNames, ColumnDisplayName, LayoutAttribute and maybe the entire Annotations system. With these UI related types left outside the UI namespace, I think introducing such a namespace does not really give us a more intuitive structure.

This warning also has some guidance on the use of namespaces in .NET: https://docs.microsoft.com/en-gb/previous-versions/visualstudio/visual-studio-2015/code-quality/ca1020-avoid-namespaces-with-few-types?view=vs-2015

File: Engine/ChildItemVisibility.cs [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+            VisibilityProperty.SetValue(obj, expanded switch
+            {
+                null => null,
+                true => "expand",
+                false => "collapse"
+            });
+        }
+        /// <summary>  Gets the current visibility state. If not set it will return null. </summary>
+        /// <param name="obj">The object from which to get visibility.</param>
+        public static bool? GetVisibility(object obj)
```
Comment (AsgerIversen) [inline Engine/ChildItemVisibility.cs:42]: Should we make an enum for this instead of a bool?. Similar to WPF vilibility. That should also make it show up nicer in xml without manually doing string stuff.

**Review by AsgerIversen — CHANGES_REQUESTED** [review]
Looks good. One small thing...

File: Engine.UnitTests/ChildItemVisibilityTest.cs [hunk 3]
```diff
@@ -0,0 +1,31 @@
+using NUnit.Framework;
+using OpenTap.Plugins.BasicSteps;
+
+namespace OpenTap.UnitTests
+{
+    [TestFixture]
+    public class ChildItemVisibilityTest
+    {
+        [Test]
+        public void TestSerializeUiFolding()
```
Comment (alnlarsen) [inline Engine.UnitTests/ChildItemVisibilityTest.cs:10]: TestSerializeChildItemVisibility?

File: Engine/ChildItemVisibility.cs [hunk 4]
```diff
@@ -0,0 +1,49 @@
+using System;
+using System.ComponentModel;
+using System.Xml.Serialization;
+
+namespace OpenTap
+{
+    /// <summary>  Child item visibility implements the concept of showing or hiding a child item. This could for example be the child steps of a test step. </summary>
+    public static class ChildItemVisibility
+    {
+        // The UI Folding property can have 3 states, null, collapsed and expanded.
```
Comment (alnlarsen) [inline Engine/ChildItemVisibility.cs:10]: This comment is no longer relevant

File: Engine/ChildItemVisibility.cs [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+        {
+            /// <summary> Child items are visible. This is the default state. </summary>
+            Visible, 
+            /// <summary> Child items are collapsed.</summary>
+            Collapsed
+        }
+        
+        internal static readonly DynamicMember VisibilityProperty = new DynamicMember
+        {
+            Name = "UI.Visibility",
```
Comment (alnlarsen) [inline Engine/ChildItemVisibility.cs:25]: ChildItem.Visibility?

File: Engine/ChildItemVisibility.cs [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+
+        /// <summary>  Set visibility to collapsed or Visible. </summary>
+        /// <param name="obj">The object for which to set visibility.</param>
+        /// <param name="visibility"> </param>
+        public static void SetVisibility(object obj, Visibility visibility)
+        {
+            VisibilityProperty.SetValue(obj, visibility);
+        }
+        
+        /// <summary>  Sets the current collapsed or folding state. If not set it will return null. </summary>
```
Comment (alnlarsen) [inline Engine/ChildItemVisibility.cs:42]: This cannot return null, right?

File: Engine/ChildItemVisibility.cs [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+        /// <param name="obj">The object from which to get folding.</param>
```
Comment (alnlarsen) [inline Engine/ChildItemVisibility.cs:43]: folding -> visibility

**Review by alnlarsen — CHANGES_REQUESTED** [review]
It seems there are a lot of renaming issues

**Review by alnlarsen — APPROVED** [review]
Looks good!

**Review by alnlarsen — APPROVED** [review]

**Review by AsgerIversen — APPROVED** [review]
