### PR TITLE
CliUserInputInterface: Read from stdin pipe if no terminal is connected

### LINKED ISSUE #1092: CliUserInputImplementation: Handle case when no TTY is connected
When running in an environment with no stdin connected, the current implementation just hangs. We should detect if there is no stdin, and read from the stdin pipe.

I saw this exception in a GitHub pipeline: `InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
`

### PR DESCRIPTION
**Pull request by alnlarsen**
This adds a separate reader mode for the CLI user input handler. This reader mode is automatically used when `Console.IsInputRedirected` is set. This will be set whenever the the stdin of the process is not attached to a terminal. 

| Input Mode | Description |
| --- | --- |
| Piped | Stdin is read line by line. UserInput request `n` gets the value of line `n`. If EOF is reached, and there are more UserInput requests, an EOF exception is thrown. |
| Stdin | (unchanged) Stdin is continously read line by line by a background thread. When a user input arrives, it blocks until it times out, or a line is produced by the worker thread. |

Closes #1092

### CODE REVIEW

File: Engine/UserInput.cs [hunk 1]
```diff
@@ -127,7 +127,7 @@ public class CliUserInputInterface : IUserInputInterface
 
         void IUserInputInterface.RequestUserInput(object dataObject, TimeSpan timeout, bool modal)
         {
-            if(readerThread == null)
+            if(readerThread == null && Console.IsInputRedirected == false)
```
[the remark this answers is not in the document]
Comment (rmadsen-ks) [reply Engine/UserInput.cs:130]: Also, lets say i want to pipe some input into the program, there may be ways to do this and I think we should support that or it would be a somewhat difficult to explain behavior.

Alternatively, we could have an extra command line argument that can be used for when it is wanted to pipe input into the application. Just like if you do `git diff`, it behaves differently from when you do `git diff|grep something`.

**Review by rmadsen-ks — CHANGES_REQUESTED** [review]

File: Engine/UserInput.cs [hunk 2]
```diff
@@ -317,7 +316,12 @@ bool isBrowsable(IMemberData m)
                     else if(string.IsNullOrEmpty(str.Value) == false)
                         Console.Write($"({str.Value}): ");
                     else Console.WriteLine(":");
-                    
+
+                    if (Console.IsInputRedirected)
+                    {
+                        log.Warning("\nStandard Input is redirected. Default option chosen.\n");
```
Comment (rmadsen-ks) [inline Engine/UserInput.cs:322]: I don't think we should emit a warning. Whatabout writing something a bit more useful as an Info message.

e.g "Selecting '{value}' for '{property}'?

**Review by rmadsen-ks — CHANGES_REQUESTED** [review]

File: Engine/Cli/RunCliAction.cs [hunk 3]
```diff
@@ -148,9 +148,13 @@ public int Execute(CancellationToken cancellationToken)
             }
 
 
-            if (!NonInteractive && UserInput.Interface == null)
+            if (UserInput.Interface == null)
```
Comment (rmadsen-ks) [inline Engine/Cli/RunCliAction.cs:151]: I like the idea of the 4 modes in your description. Why don't we make those 4 modes arguments for CliUserInputInterface to make it explicit when the class is created and move that state more up?

**Review by rmadsen-ks — CHANGES_REQUESTED** [review]

**Comment by alnlarsen** [comment]
I have reverted the whole 'non-interactive cli reader' because I don't think the concept makes a lot of sense. I can't imagine this being used for CLI actions with more than a single user input anyway. In all other cases, 'non-interactive' makes more sense.

File: Engine/UserInput.cs [hunk 4]
```diff
@@ -318,16 +373,15 @@ bool isBrowsable(IMemberData m)
                         Console.Write($"({str.Value}): ");
                     else Console.WriteLine(":");
                     
-                    
                     if (secure)
                     {
-                        var read2 = (awaitReadLine(timeoutAt, true) ?? "").Trim();
+                        var read2 = (awaitReadLine(timeoutAt, true)).Trim();
```
Comment (rmadsen-ks) [inline Engine/UserInput.cs:378]: looks like awaitReadLine could previously return null. This is no longer the case?

File: Engine/UserInput.cs [hunk 5]
```diff
@@ -398,11 +467,14 @@ string awaitReadLine(DateTime timeOut, bool secure)
             }
         }
 
+        // These must both be static, because concurrent reader threads will wreak havoc by simulatenously reading from stdin
```
Comment (rmadsen-ks) [inline Engine/UserInput.cs:470]: They must be static but arent?

**Review by rmadsen-ks — CHANGES_REQUESTED** [review]
Can we add a test to the "Test test plans" which verifies the new piped behavior?

File: Engine/UserInput.cs (hunk 5 above)
Comment (alnlarsen) [reply Engine/UserInput.cs:470]: I will remove the outdated comment :)

File: Engine/UserInput.cs (hunk 4 above)
Comment (alnlarsen) [reply Engine/UserInput.cs:378]: No, `awaitReadLine` was used in two places, and both places used null propagation, so I moved the null propagation into `awaitReadLine` instead

**Comment by rmadsen-ks** [comment]
I think we need to investigate the surprising behavior with BOM and github pipelines before implementing code specifically to handle that.

**Comment by alnlarsen** [comment]
@rmadsen-ks I have removed the special handling for utf-8 bom. I also discovered how to reproduce the problem locally. 

This is an old bug in .NET Framework which will be solved by moving to .NET 6/8. The default codepage in Windows is CP-437, but Github Runners use CP-65001 which is UTF-8.

By running `chcp 65001` in a terminal, and then running the `test-piped-input` plan, the issue can be reproduced locally. I verified that the issue does not reproduce if I run `tap` with .NET 6.

**Review by rmadsen-ks — APPROVED** [review]
Looks good!
