### PR TITLE
1435 Package Download Prerelease bug: Fix

### LINKED ISSUE #1435: package commands AnyRelease version sometimes include prerelease versions
To reproduce it call this and observe the resulting version

```package download --os Windows -f Demonstration --no-cache```

```
00:00:01.666 : PackageAction : Debug       : Downloading 'Demonstration' version '9.1.0-alpha.1.3+c212b601.2-publish-test-package' from 'https://packages.opentap.io'
00:00:02.243 : PackageAction : Information : Downloaded 'Demonstration' to 'C:\Keysight\Development\KS8400\bin\Debug\Demonstration.9.1.0-alpha.1.3+c212b601.2-publish-test-package.Windows,Linux.TapPackage'. [578 ms]
00:00:02.247 : PackageCache  : Debug       : Package cached in C:\Users\romadsen\AppData\Local\OpenTap\PackageCache\Demonstration.9.1.0-alpha.1.3+c212b601.2-publish-test-package.Windows,Linux.TapPackage.
```

This **should** have downloaded **release** version (9.0.6) but an alpha got downloaded.

Note: It seems this was caused by the graphql query version being not set (any prerelease) as opposed to be set to an empty string (any release).

### PR DESCRIPTION
**Pull request by rmadsen-ks**
Fixed the issue by setting an empty query parameter version string when AnyPrerelease was selected.

Close #1435

### CODE REVIEW

File: Package/Repositories/HttpPackageRepository.cs [hunk 1]
```diff
@@ -378,8 +378,14 @@ public string[] GetPackageNames(CancellationToken cancellationToken, params IPac
...
-            if (version != null && version != VersionSpecifier.AnyRelease)
-                parameters["version"] = version.ToString();
+            if (version != null)
+            {
+                if (version == VersionSpecifier.AnyRelease)
+                    // AnyRelease in query parameters is an empty string.
+                    parameters["version"] = "";
+                else
+                    parameters["version"] = version.ToString();     
+            }
```
Comment (alnlarsen) [inline Package/Repositories/HttpPackageRepository.cs:388]: AnyPrerelease.ToString() is actually "":

```csharp
        public override string ToString()
        {
            if (this == VersionSpecifier.Any)
                return "Any";
            if (this == VersionSpecifier.AnyRelease)
                return "";
...
``

**Review by alnlarsen — CHANGES_REQUESTED** [review]
We can simplify a bit
