### PR TITLE
655 TestStep Break Exception

### LINKED ISSUE #655: TestStepBreakException due to break condition from child test steps not catchable in parent
This was introduced by commit 071bd21614acdb3aa1bf0c4f64c89d3b4f34baea (#292)

### PR DESCRIPTION
**Pull request by rmadsen-ks**
This PR fixes a breaking change introduced in 9.17.

If the behavior from 9.18 is wanted new API points can be used for that.

Closes #655

### CODE REVIEW

File: doc/Developer Guide/Test Step/Readme.md [hunk 1]
```diff
@@ -334,7 +335,42 @@ For different approaches to publishing results, see the examples in:
...
+    public override void Run()
+    {
+        // Insert here things to do before running child steps 
+        RunChildSteps();
+        // Insert here things to do after running child steps.
+    }
+```
+
+`RunChildSteps` will take care of setting the verdict of the calling test step based on the verdict of the child test steps. The default algorithm here is to take the most severe verdict and use that for the parent test step. 
+For example, if the child test steps has verdict Pass, Inconclusive and Fail, the parent test step will get the Fail verdict.
```
Comment (alnlarsen) [inline doc/Developer Guide/Test Step/Readme.md:357]:
```suggestion
For example, if the child test steps have verdicts Pass, Inconclusive and Fail, the parent test step will get the Fail verdict.   
```

File: doc/Developer Guide/Test Step/Readme.md [hunk 2]
```diff
@@ -334,7 +335,42 @@ For different approaches to publishing results, see the examples in:
...
+        // Insert here things to do before running child steps 
+        RunChildSteps();
+        // Insert here things to do after running child steps.
+    }
+```
+
+`RunChildSteps` will take care of setting the verdict of the calling test step based on the verdict of the child test steps. The default algorithm here is to take the most severe verdict and use that for the parent test step. 
+For example, if the child test steps has verdict Pass, Inconclusive and Fail, the parent test step will get the Fail verdict.   
+
+`RunChildSteps` may throw an exception, this happens if the break conditions for the parent test step are satisfied.
```
Comment (alnlarsen) [inline doc/Developer Guide/Test Step/Readme.md:359]:
```suggestion
`RunChildSteps` may throw an exception. This happens if the break conditions for the parent test step are satisfied. 
```

File: doc/Developer Guide/Test Step/Readme.md [hunk 3]
```diff
@@ -334,7 +335,42 @@ For different approaches to publishing results, see the examples in:
...
+        RunChildSteps();
+        // Insert here things to do after running child steps.
+    }
+```
+
+`RunChildSteps` will take care of setting the verdict of the calling test step based on the verdict of the child test steps. The default algorithm here is to take the most severe verdict and use that for the parent test step. 
+For example, if the child test steps has verdict Pass, Inconclusive and Fail, the parent test step will get the Fail verdict.   
+
+`RunChildSteps` may throw an exception, this happens if the break conditions for the parent test step are satisfied. 
+If the break conditions are satisfied due to an exeception being thrown, resulting in an Error verdict, the same exception will be thrown.
```
Comment (alnlarsen) [inline doc/Developer Guide/Test Step/Readme.md:360]:
```suggestion
If the break conditions are satisfied due to an exception being thrown, resulting in an Error verdict, the same exception will be thrown.
```

File: doc/Developer Guide/Test Step/Readme.md [hunk 4]
```diff
@@ -334,7 +335,42 @@ For different approaches to publishing results, see the examples in:
...
+To avoid this behavior the overload `RunChildSteps(throwOnBreak: false)` can be used, but the exceptions are still available from the returned list of test step runs.
```
Comment (alnlarsen) [inline doc/Developer Guide/Test Step/Readme.md:361]:
```suggestion
To avoid this behavior, the overload `RunChildSteps(throwOnBreak: false)` can be used, but the exceptions are still available from the returned list of test step runs.
```

File: doc/Developer Guide/Test Step/Readme.md [hunk 5]
```diff
@@ -334,7 +335,42 @@ For different approaches to publishing results, see the examples in:
...
+
+To override a verdict set by `RunChildSteps` the exception need to be caught or `throwOnBreak` needs to be set. After this the `Verdict` property can be set directly.
```
Comment (alnlarsen) [inline doc/Developer Guide/Test Step/Readme.md:363]:
```suggestion
To override a verdict set by `RunChildSteps`, the exception must be caught, or `throwOnBreak` must be set. After this, the `Verdict` property can be set directly.
```

File: doc/Developer Guide/Test Step/Readme.md [hunk 6]
```diff
@@ -334,7 +335,42 @@ For different approaches to publishing results, see the examples in:
...
+```cs
+    public override void Run()
+    {
+        RunChildSteps(throwOnBreak: false);
+        Verdict = Verdict.Pass; // force the verdict to be 'Pass'
+    }
+```
+
+Child test steps can be run in a separate thread. This should be done with the TapThread.Start method. Before returning from the parent step the child step thread should be waited for or alternatively this should be done in a Defer operation. A great example of using parallelism can be found in the [Parallel Step](https://github.com/opentap/opentap/blob/main/BasicSteps/ParallelStep.cs).
```
Comment (alnlarsen) [inline doc/Developer Guide/Test Step/Readme.md:372]:
```suggestion
Child test steps can be run in a separate thread. This should be done with the TapThread.Start method. Before returning from the parent step, the child step thread should be waited for, or alternatively this should be done in a Defer operation. A great example of using parallelism can be found in the [Parallel Step](https://github.com/opentap/opentap/blob/main/BasicSteps/ParallelStep.cs).
```

File: doc/Developer Guide/Test Step/Readme.md [hunk 7]
```diff
@@ -334,7 +335,42 @@ For different approaches to publishing results, see the examples in:
...
 -	`TAP_PATH\Packages\SDK\Examples\PluginDevelopment\TestSteps\PublishResults`
 
-	
+## Child Test Steps
+
+Test step can have any number of child test steps. Exactly which can be controlled by using `AllowAnyChildAttribute`, and `AllowChildOfType`. 
+
+To execute child test steps within a test step run, the RunChildStep method can be used to run a single child step or RunChildSteps can be used to run all of them.
+
+Depending on the verdict of the child steps, the break condition setting of the parent step and the way RunChildSteps is called there are a number of different ways that the control flow will be affected.
```
Comment (alnlarsen) [inline doc/Developer Guide/Test Step/Readme.md:344]:
```suggestion
Depending on the verdict of the child steps, the break condition setting of the parent step, and the way RunChildSteps is called, there are a number of different ways that the control flow will be affected.
```

File: Engine/TestStep.cs [hunk 8]
```diff
@@ -707,12 +747,17 @@ public static IEnumerable<TestStepRun> RunChildSteps(this ITestStep Step, TestPl
...
                             }
                         }
-                        // if skip to next step, dont add it to the wait queue.
+                        // if skip to next step, don't add it to the wait queue.
                     }
                     if (run.BreakConditionsSatisfied())
                     {
                         run.LogBreakCondition();
-                        break;
+                        if (throwOnBreak)
```
Comment (alnlarsen) [inline Engine/TestStep.cs:755]: Do we need to break here if `throwOnBreak == false` ?

**Review by alnlarsen — CHANGES_REQUESTED** [review]

**Comment by alnlarsen** [comment]
I think the implementation looks good. I just have one question and a few corrections.

File: Engine/TestStepRun.cs [hunk 9]
```diff
@@ -59,7 +59,10 @@ public Verdict Verdict
             }
             protected internal set => Parameters.SetIndexed((nameof(Verdict), GROUP), ref verdictIndex, value);
         }
-
+        
+        /// <summary> Exception causing the Verdict to be 'Error' in any. </summary>
```
Comment (rmadsen-ks) [inline Engine/TestStepRun.cs:63]:
```suggestion
        /// <summary> Exception causing the Verdict to be 'Error'. </summary>
```
