### PR TITLE
898 stepnameannotationvalue on teststep throws an exception

### LINKED ISSUE #898: StepNameAnnotation.Value on TestStep[] throws an exception
**Describe the bug**
StepNameAnnotation.Value on TestStep[] throws an exception

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.19

**Expected behavior**

The annotation should not throw an exception, instead the value should be null if all teststeps dont have the same name, and otherwise it should be the shared name of all the teststeps in the array.

### PR DESCRIPTION
**Pull request by frederikja163**
Closes #898

### CODE REVIEW

File: Engine/Annotations/Annotation.cs [hunk 1]
```diff
@@ -1667,17 +1667,23 @@ public string Value
...
-                        value = (ITestStep)annotation.Get<IObjectValueAnnotation>().Value;
+                        value = annotation.Get<IObjectValueAnnotation>().Value;
                     }
 
-                    return value.GetFormattedName();
+                    if (value is ITestStep step)
+                    {
+                        return step.GetFormattedName();
+                    }
+                    IEnumerable<ITestStep> steps = (IEnumerable<ITestStep>)value;
```
Comment (alnlarsen) [inline Engine/Annotations/Annotation.cs:1684]: Can we type match here instead of casting? And do something a bit more defensive than `steps.First()`

**Review by alnlarsen — CHANGES_REQUESTED** [review]
This looks good. Can you make one minor change?

**Review by alnlarsen — APPROVED** [review]
Looks good!
