### PR TITLE
AssemblyFinder will skip a subdirectory if it appears to be a OpenTap installation.

### LINKED ISSUE #1571: Refuse to create new installations inside existing installations
This is not a new issue. We have known that this doesn't work for several years since we have a quite old check in the `sdk new project` template for this very reason.

Someone had a problem recently because they are building into a subdirectory of `$TAP_PATH`. It looks like the Serializer and the Assembly Resolver will not always agree on which instance of types it should use. This of course causes issues when we try to create an instance of a type from an assembly which is not loaded.

I tried reproducing this on 9.24, 9.23, and 9.22, but I suspect it goes back further. 

** Steps to reproduce **
1. `tap image install 'OpenTAP:9.24' -t .`
2. `tap image install 'OpenTAP:9.21' -t subdir`
3. `./tap package install 'TUI'`
4. `./tap package list -i`

### PR DESCRIPTION
**Pull request by Oeh1995**
Closes #1571

### CODE REVIEW

File: Engine/AssemblyFinder.cs [hunk 1]
```diff
@@ -97,6 +97,8 @@ private void SyncFiles()
                             {
                                 if (StrEq(subDir.Name, "obj"))
                                     continue; // skip obj subfolder
+                                if (subDir.GetFiles("Tap.exe").Any())
+                                    continue; // skip subdirectory if it appears to be an opentap installation
```
Comment (alnlarsen) [inline Engine/AssemblyFinder.cs:101]: `tap.exe` only exists on Windows. We should probably check `OpenTap.dll` instead.

File: Engine/AssemblyFinder.cs [hunk 2]
```diff
@@ -97,6 +97,8 @@ private void SyncFiles()
                             {
                                 if (StrEq(subDir.Name, "obj"))
                                     continue; // skip obj subfolder
+                                if (subDir.GetFiles("OpenTap.dll").Any())
+                                    continue; // skip subdirectory if it appears to be an opentap installation
```
Comment (alnlarsen) [inline Engine/AssemblyFinder.cs:101]: We should probably log a warning when this happens the first time for a given directory.

File: Engine/AssemblyFinder.cs [hunk 3]
```diff
@@ -97,6 +97,11 @@ private void SyncFiles()
                             {
                                 if (StrEq(subDir.Name, "obj"))
                                     continue; // skip obj subfolder
+                                if (subDir.GetFiles("OpenTap.dll").Any())
+                                {
+                                    log.Warning("Found OpenTap installation in subdirectory: '{0}'", subDir.Name);
```
Comment (alnlarsen) [inline Engine/AssemblyFinder.cs:102]: We need to inform the user that plugins will not be loaded from this subdirectory since this is new behavior. Nested installations can cause unexpected behavior and are not supported.

**Comment by alnlarsen** [comment]
I have been thinking about this a bit more. I think it is a risky change to completely ignore subfolders containing 'opentap.dll'. This is risky because it's possible to add additional search paths using `PluginManager.DirectoriesToSearch.Add(...)`, so I think the best option is just to ensure the serializer does not pick a different version of e.g. OpenTap types than the version which is currently loaded.

I think we should still follow Rolfs original suggestion of throwing an exception when trying to deploy a new installation into a subdirectory of OpenTAP.

**Comment by Oeh1995** [comment]
I think we should create a new issue dealing with the Serializer and then keep going forward with throwing and exception if you try to install opentap in a subdirectory of another installation.

File: Package/PackageActions/Install.cs [hunk 4]
```diff
@@ -109,8 +109,14 @@ private int DoExecute(CancellationToken cancellationToken)
         {
             if (Target == null)
                 Target = FileSystemHelper.GetCurrentInstallationDirectory();
+            if (NestedTapInstallation() == true)
```
Comment (alnlarsen) [inline Package/PackageActions/Install.cs:112]: No need to check if a bool is == true

File: Package/PackageActions/IsolatedPackageAction.cs [hunk 5]
```diff
@@ -78,6 +78,30 @@ public override int Execute(CancellationToken cancellationToken)
...
+                    filePath = Path.Combine(parentDir.FullName, "OpenTap.dll");
+                    if (File.Exists(filePath))
+                    {
+                        fileExists = true;
+                        break;
+                    }
+                    parentDir = parentDir.Parent;
+                }
+            }
+            return fileExists;
```
Comment (alnlarsen) [inline Package/PackageActions/IsolatedPackageAction.cs:101]: We can make this a lot simpler. Maybe something like:

```cs
var dir = new DirectoryInfo(target).Parent;
while (dir != null)
{
    if (dir.EnumerateFiles("OpenTap.dll").Any())
        return true;
    dir = dir.Parent;
}
return false;
```

**Review by alnlarsen — APPROVED** [review]
This works great now!
